### ISSUE TITLE
Customize VM disks

### ISSUE THREAD

**Issue by mkuzmin** [mkuzmin/terraform-vsphere#9]
- Create a new disk
- Attach an existing disk from datasotre
- Resize current disk

**Comment by rogierlommers** [comment]
Regarding your vsphere-terraform-provider: we are going to use this plugin to provide virtual machines on our vmware cluster. We have a couple of development teams who create applications. These applications need to run on a virtual machine and we use Terraform within a Dockerized container to create/maintain the infrastructure. Your binary is part of that container.

What are your concrete plans for supporting the creation of storage? Basically the final feature we need in order to start using your plugin is to be able to create local storage to a freshly cloned VM. The storage should be placed on the local store. It would be great if you can build this / inform us about your planning. And of course: if you need more info, please don't hesitate to contact me.

p.s., somehow offtopic, but:
Again, thanks for your v0.4 release; it's working fine here. And for your info: we're also able to build our own static binaries now, by running `CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags '-s' sources.go`. Maybe this is useful for you in case you don't want to use gox.

**Comment by mkuzmin** [comment]
So, do you need to increase a size of a current disk, or add a second empty disk?

**Comment by rogierlommers** [comment]
We create virtual machines based upon a template. These templates do NOT contain disks. So after cloning from a template, we want to add a (primary) hard disk to the machine on the local store.

**Comment by mkuzmin** [comment]
Sorry, but I still do not understand the use case.
If a machine does not have a disk, how OS is started there?

**Comment by oneingan** [comment]
I also would like to add additional disks. We have standarized additional
disk sizes for different applications.

And depending of SCSI # controller selected is for one function or another.

**Comment by rogierlommers** [comment]
https://github.com/mkuzmin/terraform-vsphere/issues/9#issuecomment-88058896

We have a couple of templates, for each environment a specific template (TST, ACC, PRO). Based on the machine.id (which is a property we set with the `configuration_parameters`-parameter) the virtual machine boots and the PXE boot process takes care of automated installation of the OS. But before we can power-on the machine, we need to add a hard disk. It would be great if you can add the possibility to specify a hard disk in the terraform file. It is very important that the hard disk will be created on the same host as where the VM is deployed to.

```
resource "vsphere_virtual_machine" "eddy-app1" {
  name =  "bla1-from-vm"
  folder = "/linux"
  image = "/@Templates/dummy-template"
  host = "cluster-poc"
  linked_clone = false
  cpus = 2
  memory = 4096
  power_on = false
  configuration_parameters = {
      machine.id = "bla-001#custom-id#blablabla.com"
  }
}
```

Please let me know if something is unclear.

**Comment by mkuzmin** [comment]
Aha, so you need a new empty disk.
I'll look into this.

**Comment by rogierlommers** [comment]
Would be great; if you need info.. just let me know!

**Comment by mkuzmin** [comment]
@VladRassokhin: creating a new disk is the most valuable feature.
[vSphere management SDK](https://developercenter.vmware.com/web/sdk/60/vsphere-management) contains `VMDiskCreate.java` example.

**Comment by mkuzmin** [comment]
The plugin is deprecated. No more changes are planned.
